// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type JobQueue struct {
	ID           string
	QueueName    string
	JobType      string
	Body         []byte
	Priority     int64
	VisibleAfter int64
	CreatedAt    int64
	RetryCount   int64
	MaxRetries   int64
	CompletedAt  sql.NullInt64
}

type JobQueueDlq struct {
	ID         string
	QueueName  string
	JobType    string
	Body       []byte
	Priority   int64
	CreatedAt  int64
	FailedAt   int64
	RetryCount int64
	Error      string
}
