// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queue.sql

package db

import (
	"context"
	"database/sql"
)

const claimJob = `-- name: ClaimJob :one
UPDATE job_queue
SET visible_after = ?,
    claimed_at = ?,
    claimed_by = ?
WHERE id = (
    SELECT jq.id FROM job_queue jq
    WHERE jq.queue_name = ?
      AND jq.completed_at IS NULL
      AND jq.visible_after <= ?
      AND (
        jq.retry_count < jq.max_retries
        OR (jq.max_retries = 0 AND jq.retry_count = 0)
      )
    ORDER BY jq.priority DESC, jq.created_at ASC
    LIMIT 1
)
RETURNING id, job_key, queue_name, job_type, body, metadata, priority, visible_after, created_at, claimed_at, claimed_by, retry_count, max_retries, completed_at, terminal_code, terminal_summary, result_json
`

type ClaimJobParams struct {
	VisibleAfter   int64
	ClaimedAt      sql.NullInt64
	ClaimedBy      string
	QueueName      string
	VisibleAfter_2 int64
}

// Atomically claim the next available pending job.
func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (JobQueue, error) {
	row := q.db.QueryRowContext(ctx, claimJob,
		arg.VisibleAfter,
		arg.ClaimedAt,
		arg.ClaimedBy,
		arg.QueueName,
		arg.VisibleAfter_2,
	)
	var i JobQueue
	err := row.Scan(
		&i.ID,
		&i.JobKey,
		&i.QueueName,
		&i.JobType,
		&i.Body,
		&i.Metadata,
		&i.Priority,
		&i.VisibleAfter,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.RetryCount,
		&i.MaxRetries,
		&i.CompletedAt,
		&i.TerminalCode,
		&i.TerminalSummary,
		&i.ResultJson,
	)
	return i, err
}

const cleanupCompletedJobs = `-- name: CleanupCompletedJobs :exec
DELETE FROM job_queue WHERE completed_at IS NOT NULL AND completed_at < ?
`

// Delete completed jobs older than the given timestamp.
func (q *Queries) CleanupCompletedJobs(ctx context.Context, completedAt sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, cleanupCompletedJobs, completedAt)
	return err
}

const completeJob = `-- name: CompleteJob :execresult
UPDATE job_queue SET completed_at = ? WHERE id = ?
`

type CompleteJobParams struct {
	CompletedAt sql.NullInt64
	ID          string
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, completeJob, arg.CompletedAt, arg.ID)
}

const completeJobWithResult = `-- name: CompleteJobWithResult :execresult
UPDATE job_queue
SET completed_at = ?,
    terminal_code = ?,
    terminal_summary = ?,
    result_json = ?
WHERE id = ?
`

type CompleteJobWithResultParams struct {
	CompletedAt     sql.NullInt64
	TerminalCode    string
	TerminalSummary string
	ResultJson      string
	ID              string
}

func (q *Queries) CompleteJobWithResult(ctx context.Context, arg CompleteJobWithResultParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, completeJobWithResult,
		arg.CompletedAt,
		arg.TerminalCode,
		arg.TerminalSummary,
		arg.ResultJson,
		arg.ID,
	)
}

const countCompletedJobs = `-- name: CountCompletedJobs :one
SELECT COUNT(*) FROM job_queue WHERE queue_name = ? AND completed_at IS NOT NULL
`

func (q *Queries) CountCompletedJobs(ctx context.Context, queueName string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCompletedJobs, queueName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDLQJobs = `-- name: CountDLQJobs :one
SELECT COUNT(*) FROM job_queue_dlq WHERE queue_name = ?
`

func (q *Queries) CountDLQJobs(ctx context.Context, queueName string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDLQJobs, queueName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingJobs = `-- name: CountPendingJobs :one
SELECT COUNT(*) FROM job_queue WHERE queue_name = ? AND completed_at IS NULL
`

func (q *Queries) CountPendingJobs(ctx context.Context, queueName string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingJobs, queueName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDLQJob = `-- name: DeleteDLQJob :exec
DELETE FROM job_queue_dlq WHERE id = ?
`

func (q *Queries) DeleteDLQJob(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDLQJob, id)
	return err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM job_queue WHERE id = ?
`

func (q *Queries) DeleteJob(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteJob, id)
	return err
}

const getDLQJob = `-- name: GetDLQJob :one
SELECT id, job_key, queue_name, job_type, body, metadata, priority, created_at, failed_at, claimed_at, claimed_by, retry_count, error, terminal_code, terminal_summary, result_json FROM job_queue_dlq WHERE id = ?
`

func (q *Queries) GetDLQJob(ctx context.Context, id string) (JobQueueDlq, error) {
	row := q.db.QueryRowContext(ctx, getDLQJob, id)
	var i JobQueueDlq
	err := row.Scan(
		&i.ID,
		&i.JobKey,
		&i.QueueName,
		&i.JobType,
		&i.Body,
		&i.Metadata,
		&i.Priority,
		&i.CreatedAt,
		&i.FailedAt,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.RetryCount,
		&i.Error,
		&i.TerminalCode,
		&i.TerminalSummary,
		&i.ResultJson,
	)
	return i, err
}

const getDLQJobByKey = `-- name: GetDLQJobByKey :one
SELECT id, job_key, queue_name, job_type, body, metadata, priority, created_at, failed_at, claimed_at, claimed_by, retry_count, error, terminal_code, terminal_summary, result_json FROM job_queue_dlq WHERE queue_name = ? AND job_key = ?
`

type GetDLQJobByKeyParams struct {
	QueueName string
	JobKey    string
}

func (q *Queries) GetDLQJobByKey(ctx context.Context, arg GetDLQJobByKeyParams) (JobQueueDlq, error) {
	row := q.db.QueryRowContext(ctx, getDLQJobByKey, arg.QueueName, arg.JobKey)
	var i JobQueueDlq
	err := row.Scan(
		&i.ID,
		&i.JobKey,
		&i.QueueName,
		&i.JobType,
		&i.Body,
		&i.Metadata,
		&i.Priority,
		&i.CreatedAt,
		&i.FailedAt,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.RetryCount,
		&i.Error,
		&i.TerminalCode,
		&i.TerminalSummary,
		&i.ResultJson,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, job_key, queue_name, job_type, body, metadata, priority, visible_after, created_at, claimed_at, claimed_by, retry_count, max_retries, completed_at, terminal_code, terminal_summary, result_json FROM job_queue WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id string) (JobQueue, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i JobQueue
	err := row.Scan(
		&i.ID,
		&i.JobKey,
		&i.QueueName,
		&i.JobType,
		&i.Body,
		&i.Metadata,
		&i.Priority,
		&i.VisibleAfter,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.RetryCount,
		&i.MaxRetries,
		&i.CompletedAt,
		&i.TerminalCode,
		&i.TerminalSummary,
		&i.ResultJson,
	)
	return i, err
}

const getJobByKey = `-- name: GetJobByKey :one
SELECT id, job_key, queue_name, job_type, body, metadata, priority, visible_after, created_at, claimed_at, claimed_by, retry_count, max_retries, completed_at, terminal_code, terminal_summary, result_json FROM job_queue WHERE queue_name = ? AND job_key = ?
`

type GetJobByKeyParams struct {
	QueueName string
	JobKey    string
}

func (q *Queries) GetJobByKey(ctx context.Context, arg GetJobByKeyParams) (JobQueue, error) {
	row := q.db.QueryRowContext(ctx, getJobByKey, arg.QueueName, arg.JobKey)
	var i JobQueue
	err := row.Scan(
		&i.ID,
		&i.JobKey,
		&i.QueueName,
		&i.JobType,
		&i.Body,
		&i.Metadata,
		&i.Priority,
		&i.VisibleAfter,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.RetryCount,
		&i.MaxRetries,
		&i.CompletedAt,
		&i.TerminalCode,
		&i.TerminalSummary,
		&i.ResultJson,
	)
	return i, err
}

const getJobForUpdate = `-- name: GetJobForUpdate :one
SELECT id, job_key, queue_name, job_type, body, metadata, priority, visible_after, created_at, claimed_at, claimed_by, retry_count, max_retries, completed_at, terminal_code, terminal_summary, result_json FROM job_queue WHERE id = ?
`

func (q *Queries) GetJobForUpdate(ctx context.Context, id string) (JobQueue, error) {
	row := q.db.QueryRowContext(ctx, getJobForUpdate, id)
	var i JobQueue
	err := row.Scan(
		&i.ID,
		&i.JobKey,
		&i.QueueName,
		&i.JobType,
		&i.Body,
		&i.Metadata,
		&i.Priority,
		&i.VisibleAfter,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.RetryCount,
		&i.MaxRetries,
		&i.CompletedAt,
		&i.TerminalCode,
		&i.TerminalSummary,
		&i.ResultJson,
	)
	return i, err
}

const insertDLQ = `-- name: InsertDLQ :exec
INSERT INTO job_queue_dlq (
    id, job_key, queue_name, job_type, body, metadata, priority, created_at, failed_at, claimed_at, claimed_by, retry_count, error, terminal_code, terminal_summary, result_json
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertDLQParams struct {
	ID              string
	JobKey          string
	QueueName       string
	JobType         string
	Body            []byte
	Metadata        string
	Priority        int64
	CreatedAt       int64
	FailedAt        int64
	ClaimedAt       sql.NullInt64
	ClaimedBy       string
	RetryCount      int64
	Error           string
	TerminalCode    string
	TerminalSummary string
	ResultJson      string
}

func (q *Queries) InsertDLQ(ctx context.Context, arg InsertDLQParams) error {
	_, err := q.db.ExecContext(ctx, insertDLQ,
		arg.ID,
		arg.JobKey,
		arg.QueueName,
		arg.JobType,
		arg.Body,
		arg.Metadata,
		arg.Priority,
		arg.CreatedAt,
		arg.FailedAt,
		arg.ClaimedAt,
		arg.ClaimedBy,
		arg.RetryCount,
		arg.Error,
		arg.TerminalCode,
		arg.TerminalSummary,
		arg.ResultJson,
	)
	return err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO job_queue (
    id, job_key, queue_name, job_type, body, metadata, priority, visible_after, created_at, claimed_at, claimed_by, retry_count, max_retries, terminal_code, terminal_summary, result_json
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, '', 0, ?, '', '', '{}'
)
RETURNING id, job_key, queue_name, job_type, body, metadata, priority, visible_after, created_at, claimed_at, claimed_by, retry_count, max_retries, completed_at, terminal_code, terminal_summary, result_json
`

type InsertJobParams struct {
	ID           string
	JobKey       string
	QueueName    string
	JobType      string
	Body         []byte
	Metadata     string
	Priority     int64
	VisibleAfter int64
	CreatedAt    int64
	MaxRetries   int64
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (JobQueue, error) {
	row := q.db.QueryRowContext(ctx, insertJob,
		arg.ID,
		arg.JobKey,
		arg.QueueName,
		arg.JobType,
		arg.Body,
		arg.Metadata,
		arg.Priority,
		arg.VisibleAfter,
		arg.CreatedAt,
		arg.MaxRetries,
	)
	var i JobQueue
	err := row.Scan(
		&i.ID,
		&i.JobKey,
		&i.QueueName,
		&i.JobType,
		&i.Body,
		&i.Metadata,
		&i.Priority,
		&i.VisibleAfter,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.RetryCount,
		&i.MaxRetries,
		&i.CompletedAt,
		&i.TerminalCode,
		&i.TerminalSummary,
		&i.ResultJson,
	)
	return i, err
}

const insertJobUnique = `-- name: InsertJobUnique :many
INSERT INTO job_queue (
    id, job_key, queue_name, job_type, body, metadata, priority, visible_after, created_at, claimed_at, claimed_by, retry_count, max_retries, terminal_code, terminal_summary, result_json
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, '', 0, ?, '', '', '{}'
)
ON CONFLICT DO NOTHING
RETURNING id, job_key, queue_name, job_type, body, metadata, priority, visible_after, created_at, claimed_at, claimed_by, retry_count, max_retries, completed_at, terminal_code, terminal_summary, result_json
`

type InsertJobUniqueParams struct {
	ID           string
	JobKey       string
	QueueName    string
	JobType      string
	Body         []byte
	Metadata     string
	Priority     int64
	VisibleAfter int64
	CreatedAt    int64
	MaxRetries   int64
}

func (q *Queries) InsertJobUnique(ctx context.Context, arg InsertJobUniqueParams) ([]JobQueue, error) {
	rows, err := q.db.QueryContext(ctx, insertJobUnique,
		arg.ID,
		arg.JobKey,
		arg.QueueName,
		arg.JobType,
		arg.Body,
		arg.Metadata,
		arg.Priority,
		arg.VisibleAfter,
		arg.CreatedAt,
		arg.MaxRetries,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobQueue
	for rows.Next() {
		var i JobQueue
		if err := rows.Scan(
			&i.ID,
			&i.JobKey,
			&i.QueueName,
			&i.JobType,
			&i.Body,
			&i.Metadata,
			&i.Priority,
			&i.VisibleAfter,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.ClaimedBy,
			&i.RetryCount,
			&i.MaxRetries,
			&i.CompletedAt,
			&i.TerminalCode,
			&i.TerminalSummary,
			&i.ResultJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedJobs = `-- name: ListCompletedJobs :many
SELECT id, job_key, queue_name, job_type, body, metadata, priority, visible_after, created_at, claimed_at, claimed_by, retry_count, max_retries, completed_at, terminal_code, terminal_summary, result_json FROM job_queue
WHERE queue_name = ? AND completed_at IS NOT NULL
ORDER BY completed_at DESC
LIMIT ? OFFSET ?
`

type ListCompletedJobsParams struct {
	QueueName string
	Limit     int64
	Offset    int64
}

func (q *Queries) ListCompletedJobs(ctx context.Context, arg ListCompletedJobsParams) ([]JobQueue, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedJobs, arg.QueueName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobQueue
	for rows.Next() {
		var i JobQueue
		if err := rows.Scan(
			&i.ID,
			&i.JobKey,
			&i.QueueName,
			&i.JobType,
			&i.Body,
			&i.Metadata,
			&i.Priority,
			&i.VisibleAfter,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.ClaimedBy,
			&i.RetryCount,
			&i.MaxRetries,
			&i.CompletedAt,
			&i.TerminalCode,
			&i.TerminalSummary,
			&i.ResultJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDLQJobs = `-- name: ListDLQJobs :many
SELECT id, job_key, queue_name, job_type, body, metadata, priority, created_at, failed_at, claimed_at, claimed_by, retry_count, error, terminal_code, terminal_summary, result_json FROM job_queue_dlq
WHERE queue_name = ?
ORDER BY failed_at DESC
LIMIT ? OFFSET ?
`

type ListDLQJobsParams struct {
	QueueName string
	Limit     int64
	Offset    int64
}

func (q *Queries) ListDLQJobs(ctx context.Context, arg ListDLQJobsParams) ([]JobQueueDlq, error) {
	rows, err := q.db.QueryContext(ctx, listDLQJobs, arg.QueueName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobQueueDlq
	for rows.Next() {
		var i JobQueueDlq
		if err := rows.Scan(
			&i.ID,
			&i.JobKey,
			&i.QueueName,
			&i.JobType,
			&i.Body,
			&i.Metadata,
			&i.Priority,
			&i.CreatedAt,
			&i.FailedAt,
			&i.ClaimedAt,
			&i.ClaimedBy,
			&i.RetryCount,
			&i.Error,
			&i.TerminalCode,
			&i.TerminalSummary,
			&i.ResultJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingJobs = `-- name: ListPendingJobs :many
SELECT id, job_key, queue_name, job_type, body, metadata, priority, visible_after, created_at, claimed_at, claimed_by, retry_count, max_retries, completed_at, terminal_code, terminal_summary, result_json FROM job_queue
WHERE queue_name = ? AND completed_at IS NULL
ORDER BY priority DESC, created_at ASC
LIMIT ? OFFSET ?
`

type ListPendingJobsParams struct {
	QueueName string
	Limit     int64
	Offset    int64
}

func (q *Queries) ListPendingJobs(ctx context.Context, arg ListPendingJobsParams) ([]JobQueue, error) {
	rows, err := q.db.QueryContext(ctx, listPendingJobs, arg.QueueName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobQueue
	for rows.Next() {
		var i JobQueue
		if err := rows.Scan(
			&i.ID,
			&i.JobKey,
			&i.QueueName,
			&i.JobType,
			&i.Body,
			&i.Metadata,
			&i.Priority,
			&i.VisibleAfter,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.ClaimedBy,
			&i.RetryCount,
			&i.MaxRetries,
			&i.CompletedAt,
			&i.TerminalCode,
			&i.TerminalSummary,
			&i.ResultJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryJob = `-- name: RetryJob :execresult
UPDATE job_queue
SET visible_after = ?, retry_count = retry_count + 1
WHERE id = ? AND completed_at IS NULL
`

type RetryJobParams struct {
	VisibleAfter int64
	ID           string
}

// Record a failed attempt and make immediately visible.
func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, retryJob, arg.VisibleAfter, arg.ID)
}

const sweepStuckJobs = `-- name: SweepStuckJobs :many
SELECT id, job_key, queue_name, job_type, body, metadata, priority, visible_after, created_at, claimed_at, claimed_by, retry_count, max_retries, completed_at, terminal_code, terminal_summary, result_json FROM job_queue
WHERE queue_name = ?
  AND completed_at IS NULL
  AND retry_count >= max_retries
`

// Find jobs that exhausted retries but were never completed or moved to DLQ.
func (q *Queries) SweepStuckJobs(ctx context.Context, queueName string) ([]JobQueue, error) {
	rows, err := q.db.QueryContext(ctx, sweepStuckJobs, queueName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobQueue
	for rows.Next() {
		var i JobQueue
		if err := rows.Scan(
			&i.ID,
			&i.JobKey,
			&i.QueueName,
			&i.JobType,
			&i.Body,
			&i.Metadata,
			&i.Priority,
			&i.VisibleAfter,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.ClaimedBy,
			&i.RetryCount,
			&i.MaxRetries,
			&i.CompletedAt,
			&i.TerminalCode,
			&i.TerminalSummary,
			&i.ResultJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
